CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mainOrderNo` varchar(32) NOT NULL,
	`subOrderNo` varchar(32) NOT NULL,
	`productName` text,
	`productSpec` text,
	`quantity` int NOT NULL DEFAULT 1,
	`sku` varchar(64),
	`unitPrice` decimal(10,2) NOT NULL DEFAULT '0',
	`payAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`freight` decimal(10,2) NOT NULL DEFAULT '0',
	`totalDiscount` decimal(10,2) NOT NULL DEFAULT '0',
	`platformDiscount` decimal(10,2) NOT NULL DEFAULT '0',
	`merchantDiscount` decimal(10,2) NOT NULL DEFAULT '0',
	`influencerDiscount` decimal(10,2) NOT NULL DEFAULT '0',
	`serviceFee` decimal(10,2) NOT NULL DEFAULT '0',
	`payMethod` varchar(32),
	`receiver` varchar(64),
	`receiverPhone` varchar(32),
	`province` varchar(32),
	`city` varchar(32),
	`district` varchar(32),
	`address` text,
	`orderTime` timestamp,
	`payTime` timestamp,
	`shipTime` timestamp,
	`completeTime` timestamp,
	`status` varchar(32) NOT NULL DEFAULT '待发货',
	`afterSaleStatus` varchar(32),
	`cancelReason` text,
	`appChannel` varchar(32),
	`trafficSource` varchar(64),
	`orderType` varchar(32),
	`influencerId` varchar(64),
	`influencerName` varchar(128),
	`flagColor` varchar(16),
	`merchantRemark` text,
	`buyerMessage` text,
	`shopName` varchar(128) DEFAULT '滋栈官方旗舰店',
	`deleted` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `orders_subOrderNo_unique` UNIQUE(`subOrderNo`)
);
